name: package-helm-chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  
permissions:
  contents: read
  packages: write

env:
  CHART_PATH: charts/example-app

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Package chart
        run: |
          helm package ${{ env.CHART_PATH }}

      - name: Push chart to GHCR
        run: |
          CHART_NAME=$(yq '.name' ${{ env.CHART_PATH }}/Chart.yaml)
          CHART_VERSION=$(yq '.version' ${{ env.CHART_PATH }}/Chart.yaml)

          helm push \
            ${CHART_NAME}-${CHART_VERSION}.tgz \
            oci://ghcr.io/${{ github.repository_owner }}/charts