name: package-helm-chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  
permissions:
  contents: read
  packages: write

env:
  CHART_PATH: charts/example-app

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Package chart
        run: |
          helm package ${{ env.CHART_PATH }}

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy chart package
        run: |
          cp *.tgz gh-pages/

      - name: Generate index.yaml
        run: |
          helm repo index gh-pages \
            --url https://cabs-tech.github.io/charts

      - name: Commit and push
        run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .
          git commit -m "Publish chart" || exit 0
          git push